# -*- coding: utf-8 -*-
"""YOLOv8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBUT0yV3D3rGrR3ubWWrYlql5O3FG8Gq

#Выбор видеокарты (GPU) для лучшей производительности
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

"""#Импорт необходимых библиотек"""

!pip install -r requirements.txt

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

"""#Загрузка полученного датасета"""

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="WwOb9ZgMHYQf90FEXIDy")
project = rf.workspace("ivanj-roads").project("roads_uav1")
version = project.version(1)
dataset = version.download("yolov8")

"""#Необходимые файлы для отслеживания DeepSORT


"""

!gdown "https://drive.google.com/uc?id=11ZSZcG-bcbueXZC3rN08CM0qqX3eiHxf&confirm=t"
!unzip 'deep_sort_pytorch.zip'

"""#Обучение модели"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolov8s.pt data={'/content/datasets/Roads_UAV1-1'}/data.yaml epochs=10 imgsz=640 plots=True

!ls {'runs/detect/train'}

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/confusion_matrix.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/results.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/val_batch0_pred.jpg', width=600)

"""#Валидация модели"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=val model={HOME}/runs/detect/train/weights/best.pt data={'/content/datasets/Roads_UAV1-1'}/data.yaml

"""#Вывод данных с помощью модели"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model={HOME}/runs/detect/train/weights/best.pt conf=0.25 source={'/content/datasets'}/test/images save=True

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/predict/DJI_0932.JPG', width=600)